### PR TITLE
Work on summation inference

### PR DESCRIPTION
**Pull request by GeorgeR227**
Cleans up the summation inference code. This will now only propagate form types and do basic type checking.

### CODE REVIEW

**Comment by lukem12345** [comment]
@GeorgeR227 Your last few PRs have had spurious changes to lines. I guess this is because of line ending encodings or something. I think you can configure your git client to ignore these.

**Comment by GeorgeR227** [comment]
I think actually this is to do with hanging whitespace at the end of lines. My git client does tell me if the encoding are different. 

However I agree with you in that these are annoying now because they aren't the purpose of these PRs.

**Comment by GeorgeR227** [comment]
Also I'm moving this PR to #49.

**Comment by lukem12345** [comment]
> I think actually this is to do with hanging whitespace at the end of lines. My git client does tell me if the encoding are different. 

Yeah maybe spot check a few of these. It usually highlights when whitespace inside of line is added or removed.

It makes the git blame misleading when tracking things down.

**Comment by lukem12345** [comment]
Ok, maybe turn off the aggressive linting setting or just use `git add` at the command line instead.

**Comment by GeorgeR227** [comment]
I'll open a linting issue with a reference this problem. We have an issue about this in Decapodes but not here.

**Pull request closed without merging**
